import { GameApp as __GameApp } from '../legacy/context.js';
(() => {
  "use strict";

  const GameApp = __GameApp;
  const Content = GameApp.Content = GameApp.Content || {};
  const Skills = Content.Skills = Content.Skills || {};

  function buildExtraBladeSkills() {
    return [
      { name: "飞刀精通", description: "飞刀伤害 +30%", tier: 2, icon: "fan.fill", effect: (s) => { s.bladeOrbitDamage *= 1.30; } },
      { name: "刀阵扩张", description: "飞刀半径 +20", tier: 1, icon: "circle.dotted", effect: (s) => { s.bladeOrbitRadius += 20; } },
      { name: "刀舞加速", description: "飞刀旋转速度 +25%", tier: 1, icon: "timer", effect: (s) => { s.bladeOrbitSpeed *= 1.25; } },
      { name: "利刃增殖", description: "飞刀数量 +1", tier: 3, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 1; } },
      { name: "锋刃风暴", description: "飞刀数量 +3，旋转速度 +20%", tier: 4, icon: "wind", effect: (s) => { s.bladeOrbitCount += 3; s.bladeOrbitSpeed *= 1.20; } },
      { name: "巨刃", description: "飞刀体积 +35%，伤害 +15%", tier: 2, icon: "circle.fill", effect: (s) => { s.bladeOrbitScale *= 1.35; s.bladeOrbitDamage *= 1.15; } },
      { name: "寒刃", description: "飞刀命中 20% 冰冻 0.8秒", tier: 3, icon: "snowflake", effect: (s) => { s.bladeOrbitFreezeChance = Math.min(1, s.bladeOrbitFreezeChance + 0.20); s.bladeOrbitFreezeDuration = Math.max(s.bladeOrbitFreezeDuration, 0.8); } },
      { name: "灼刃", description: "飞刀命中 30% 点燃 2秒", tier: 3, icon: "flame.fill", effect: (s) => { s.bladeOrbitBurnChance = Math.min(1, s.bladeOrbitBurnChance + 0.30); s.bladeOrbitBurnDuration = Math.max(s.bladeOrbitBurnDuration, 2.0); s.bladeOrbitBurnDamage = Math.max(s.bladeOrbitBurnDamage, 4); } },
      { name: "毒刃", description: "飞刀命中 30% 中毒 3秒", tier: 3, icon: "leaf.fill", effect: (s) => { s.bladeOrbitPoisonChance = Math.min(1, s.bladeOrbitPoisonChance + 0.30); s.bladeOrbitPoisonDuration = Math.max(s.bladeOrbitPoisonDuration, 3.0); s.bladeOrbitPoisonDamage = Math.max(s.bladeOrbitPoisonDamage, 3); } },
      { name: "吸血飞刃", description: "飞刀命中 15% 吸血（伤害的 20%）", tier: 4, icon: "drop.fill", effect: (s) => { s.bladeOrbitLifestealChance = Math.min(1, s.bladeOrbitLifestealChance + 0.15); s.bladeOrbitLifestealPercent = Math.max(s.bladeOrbitLifestealPercent, 0.20); } },

      { name: "磨刃", description: "飞刀伤害 +10%", tier: 1, icon: "fan.fill", effect: (s) => { s.bladeOrbitDamage *= 1.10; } },
      { name: "淬火飞刃", description: "飞刀伤害 +20%", tier: 1, icon: "flame.fill", effect: (s) => { s.bladeOrbitDamage *= 1.20; } },
      { name: "精钢飞刀", description: "飞刀伤害 +50%", tier: 3, icon: "fan.fill", effect: (s) => { s.bladeOrbitDamage *= 1.50; } },
      { name: "陨铁飞刃", description: "飞刀伤害 +80%", tier: 4, icon: "star.fill", effect: (s) => { s.bladeOrbitDamage *= 1.80; } },
      { name: "神兵飞刀", description: "飞刀伤害 +120%", tier: 5, icon: "sparkles", effect: (s) => { s.bladeOrbitDamage *= 2.20; } },
      { name: "锋利打磨", description: "飞刀伤害 +15%，体积 +10%", tier: 1, icon: "fan.fill", effect: (s) => { s.bladeOrbitDamage *= 1.15; s.bladeOrbitScale *= 1.10; } },
      { name: "重刃术", description: "飞刀伤害 +40%，旋转速度 -10%", tier: 2, icon: "circle.fill", effect: (s) => { s.bladeOrbitDamage *= 1.40; s.bladeOrbitSpeed *= 0.90; } },
      { name: "轻刃术", description: "飞刀旋转速度 +30%，伤害 +10%", tier: 2, icon: "timer", effect: (s) => { s.bladeOrbitSpeed *= 1.30; s.bladeOrbitDamage *= 1.10; } },
      { name: "刃上淬毒", description: "飞刀伤害 +25%，命中 10% 中毒", tier: 2, icon: "leaf.fill", effect: (s) => { s.bladeOrbitDamage *= 1.25; s.bladeOrbitPoisonChance = Math.min(1, (s.bladeOrbitPoisonChance || 0) + 0.10); s.bladeOrbitPoisonDuration = Math.max(s.bladeOrbitPoisonDuration || 0, 2.0); s.bladeOrbitPoisonDamage = Math.max(s.bladeOrbitPoisonDamage || 0, 2); } },
      { name: "破甲飞刃", description: "飞刀无视 20% 敌人护甲", tier: 3, icon: "fan.fill", effect: (s) => { s.bladeOrbitArmorPen = (s.bladeOrbitArmorPen || 0) + 0.20; } },
      { name: "穿甲利刃", description: "飞刀无视 40% 敌人护甲", tier: 4, icon: "fan.fill", effect: (s) => { s.bladeOrbitArmorPen = (s.bladeOrbitArmorPen || 0) + 0.40; } },
      { name: "绝甲之刃", description: "飞刀无视 100% 敌人护甲", tier: 5, icon: "fan.fill", effect: (s) => { s.bladeOrbitArmorPen = 1.0; } },
      { name: "蓄力飞刀", description: "飞刀每旋转一圈伤害 +5%（可叠加）", tier: 3, icon: "timer", effect: (s) => { s.bladeOrbitChargeBonus = (s.bladeOrbitChargeBonus || 0) + 0.05; } },
      { name: "怒刃", description: "生命越低飞刀伤害越高（最高+100%）", tier: 4, icon: "flame.fill", effect: (s) => { s.bladeOrbitRageDamage = true; } },
      { name: "死亡飞刀", description: "飞刀对低于 20% 生命的敌人造成 3 倍伤害", tier: 5, icon: "fan.fill", effect: (s) => { s.bladeOrbitExecute = true; s.bladeOrbitExecuteThreshold = 0.20; s.bladeOrbitExecuteMult = 3.0; } },

      { name: "飞刀入门", description: "飞刀数量 +1", tier: 1, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 1; } },
      { name: "刀扇展开", description: "飞刀数量 +2", tier: 2, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 2; } },
      { name: "刀雨", description: "飞刀数量 +4", tier: 4, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 4; } },
      { name: "万刃齐发", description: "飞刀数量 +8", tier: 5, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 8; } },
      { name: "学徒飞刀", description: "飞刀数量 +1", tier: 1, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 1; } },
      { name: "双刃齐飞", description: "飞刀数量 +2", tier: 1, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 2; } },
      { name: "三刃旋风", description: "飞刀数量 +3", tier: 2, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 3; } },
      { name: "四象飞刀", description: "飞刀数量 +4", tier: 2, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 4; } },
      { name: "五行飞刃", description: "飞刀数量 +5", tier: 3, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 5; } },
      { name: "六合刀阵", description: "飞刀数量 +6", tier: 3, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 6; } },
      { name: "七星飞刀", description: "飞刀数量 +7", tier: 3, icon: "star.fill", effect: (s) => { s.bladeOrbitCount += 7; } },
      { name: "八方刀雨", description: "飞刀数量 +8，伤害 +10%", tier: 4, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 8; s.bladeOrbitDamage *= 1.10; } },
      { name: "九天飞刃", description: "飞刀数量 +9", tier: 4, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 9; } },
      { name: "十面埋伏", description: "飞刀数量 +10", tier: 4, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 10; } },
      { name: "十二连环刀", description: "飞刀数量 +12", tier: 4, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 12; } },
      { name: "十五刃风暴", description: "飞刀数量 +15，旋转速度 +15%", tier: 4, icon: "wind", effect: (s) => { s.bladeOrbitCount += 15; s.bladeOrbitSpeed *= 1.15; } },
      { name: "二十刃旋涡", description: "飞刀数量 +20", tier: 5, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 20; } },
      { name: "三十刃天幕", description: "飞刀数量 +30，体积 -20%", tier: 5, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 30; s.bladeOrbitScale *= 0.80; } },
      { name: "五十刃天罗", description: "飞刀数量 +50，体积 -40%，伤害 +30%", tier: 5, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 50; s.bladeOrbitScale *= 0.60; s.bladeOrbitDamage *= 1.30; } },
      { name: "百刃齐舞", description: "飞刀数量 +100，体积 -60%", tier: 5, icon: "sparkles", effect: (s) => { s.bladeOrbitCount += 100; s.bladeOrbitScale *= 0.40; } },
      { name: "刀阵倍增", description: "飞刀数量翻倍（当前×2）", tier: 4, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount *= 2; } },
      { name: "刀阵三倍化", description: "飞刀数量三倍化（当前×3）", tier: 5, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount *= 3; } },
      { name: "密集飞刃", description: "飞刀数量 +6，半径 -15", tier: 2, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 6; s.bladeOrbitRadius = Math.max(30, s.bladeOrbitRadius - 15); } },
      { name: "扩散飞刃", description: "飞刀数量 +4，半径 +30", tier: 3, icon: "fan.fill", effect: (s) => { s.bladeOrbitCount += 4; s.bladeOrbitRadius += 30; } },
      { name: "小刀阵", description: "飞刀半径 +10", tier: 1, icon: "circle.dotted", effect: (s) => { s.bladeOrbitRadius += 10; } },
      { name: "中刀阵", description: "飞刀半径 +30", tier: 2, icon: "circle.dotted", effect: (s) => { s.bladeOrbitRadius += 30; } },
      { name: "大刀阵", description: "飞刀半径 +50", tier: 3, icon: "circle.dotted", effect: (s) => { s.bladeOrbitRadius += 50; } },
      { name: "巨型刀阵", description: "飞刀半径 +80，伤害 +20%", tier: 4, icon: "circle.dotted", effect: (s) => { s.bladeOrbitRadius += 80; s.bladeOrbitDamage *= 1.20; } },
      { name: "天旋地转", description: "飞刀旋转速度 +50%", tier: 2, icon: "timer", effect: (s) => { s.bladeOrbitSpeed *= 1.50; } },
      { name: "极速旋刃", description: "飞刀旋转速度 +100%", tier: 3, icon: "timer", effect: (s) => { s.bladeOrbitSpeed *= 2.0; } },
      { name: "光速刀环", description: "飞刀旋转速度 +200%，伤害 +30%", tier: 5, icon: "timer", effect: (s) => { s.bladeOrbitSpeed *= 3.0; s.bladeOrbitDamage *= 1.30; } },
      { name: "微型飞刃", description: "飞刀体积 -30%，数量 +3", tier: 2, icon: "fan.fill", effect: (s) => { s.bladeOrbitScale *= 0.70; s.bladeOrbitCount += 3; } },
      { name: "巨刃II", description: "飞刀体积 +60%，伤害 +25%", tier: 3, icon: "circle.fill", effect: (s) => { s.bladeOrbitScale *= 1.60; s.bladeOrbitDamage *= 1.25; } },
      { name: "泰坦飞刃", description: "飞刀体积 +100%，伤害 +50%，速度 -20%", tier: 4, icon: "circle.fill", effect: (s) => { s.bladeOrbitScale *= 2.0; s.bladeOrbitDamage *= 1.50; s.bladeOrbitSpeed *= 0.80; } },
      { name: "双层刀阵", description: "增加第二层飞刀轨道，数量 +2，半径 +40", tier: 4, icon: "circle.dotted", effect: (s) => { s.bladeOrbitCount += 2; s.bladeOrbitRadius += 40; s.bladeOrbitDualRing = true; } },

      { name: "冰晶飞刃", description: "飞刀命中 10% 冰冻 0.5秒", tier: 1, icon: "snowflake", effect: (s) => { s.bladeOrbitFreezeChance = Math.min(1, (s.bladeOrbitFreezeChance || 0) + 0.10); s.bladeOrbitFreezeDuration = Math.max(s.bladeOrbitFreezeDuration || 0, 0.5); } },
      { name: "极寒之刃", description: "飞刀冰冻几率 +15%，冰冻时间 +0.5秒", tier: 2, icon: "snowflake", effect: (s) => { s.bladeOrbitFreezeChance = Math.min(1, (s.bladeOrbitFreezeChance || 0) + 0.15); s.bladeOrbitFreezeDuration = (s.bladeOrbitFreezeDuration || 0) + 0.5; } },
      { name: "冰封刀舞", description: "飞刀冰冻几率 +25%，冰冻持续 1.5秒", tier: 3, icon: "snowflake", effect: (s) => { s.bladeOrbitFreezeChance = Math.min(1, (s.bladeOrbitFreezeChance || 0) + 0.25); s.bladeOrbitFreezeDuration = Math.max(s.bladeOrbitFreezeDuration || 0, 1.5); } },
      { name: "绝对零度", description: "飞刀必定冰冻敌人 2秒", tier: 5, icon: "snowflake", effect: (s) => { s.bladeOrbitFreezeChance = 1.0; s.bladeOrbitFreezeDuration = Math.max(s.bladeOrbitFreezeDuration || 0, 2.0); } },
      { name: "霜刃减速", description: "飞刀命中减速敌人 30%，持续 2秒", tier: 2, icon: "snowflake", effect: (s) => { s.bladeOrbitSlowChance = Math.min(1, (s.bladeOrbitSlowChance || 0) + 0.50); s.bladeOrbitSlowAmount = 0.30; s.bladeOrbitSlowDuration = 2.0; } },
      { name: "破甲飞旋", description: "飞刀命中使敌人护甲降低25%，持续3秒", tier: 3, icon: "snowflake", effect: (s) => { s.bladeOrbitArmorShred = true; s.bladeOrbitArmorShredAmount = (s.bladeOrbitArmorShredAmount || 0) + 0.25; s.bladeOrbitArmorShredDuration = 3.0; } },
      { name: "寒气弥漫", description: "飞刀半径 +25，命中散发寒气减速周围敌人", tier: 3, icon: "snowflake", effect: (s) => { s.bladeOrbitRadius += 25; s.bladeOrbitFrostAura = true; } },
      { name: "冰刃连锁", description: "飞刀冰冻敌人时，冰冻效果扩散到附近敌人", tier: 4, icon: "snowflake", effect: (s) => { s.bladeOrbitFreezeSpread = true; } },
      { name: "冰晶爆裂", description: "冰冻的敌人被再次命中时爆炸，造成范围伤害", tier: 4, icon: "snowflake", effect: (s) => { s.bladeOrbitIceExplosion = true; } },
      { name: "永冻飞刃", description: "飞刀冰冻永久减速 10%（可叠加）", tier: 5, icon: "snowflake", effect: (s) => { s.bladeOrbitPermaFrost = true; s.bladeOrbitPermaFrostSlow = 0.10; } },

      { name: "火星飞溅", description: "飞刀命中 15% 点燃 1秒", tier: 1, icon: "flame.fill", effect: (s) => { s.bladeOrbitBurnChance = Math.min(1, (s.bladeOrbitBurnChance || 0) + 0.15); s.bladeOrbitBurnDuration = Math.max(s.bladeOrbitBurnDuration || 0, 1.0); s.bladeOrbitBurnDamage = Math.max(s.bladeOrbitBurnDamage || 0, 2); } },
      { name: "烈焰飞刀", description: "飞刀点燃几率 +20%，燃烧伤害 +3", tier: 2, icon: "flame.fill", effect: (s) => { s.bladeOrbitBurnChance = Math.min(1, (s.bladeOrbitBurnChance || 0) + 0.20); s.bladeOrbitBurnDamage = (s.bladeOrbitBurnDamage || 0) + 3; } },
      { name: "焚天刃舞", description: "飞刀必定点燃，燃烧持续 3秒", tier: 4, icon: "flame.fill", effect: (s) => { s.bladeOrbitBurnChance = 1.0; s.bladeOrbitBurnDuration = Math.max(s.bladeOrbitBurnDuration || 0, 3.0); s.bladeOrbitBurnDamage = Math.max(s.bladeOrbitBurnDamage || 0, 6); } },
      { name: "火焰爆发", description: "燃烧的敌人受到飞刀额外 60% 伤害", tier: 3, icon: "flame.fill", effect: (s) => { s.bladeOrbitBurnBonusDamage = (s.bladeOrbitBurnBonusDamage || 1) * 1.60; } },
      { name: "引爆", description: "飞刀命中燃烧的敌人时引发爆炸", tier: 4, icon: "flame.fill", effect: (s) => { s.bladeOrbitBurnExplosion = true; } },
      { name: "灰烬之刃", description: "飞刀点燃伤害 +8，持续时间 +1秒", tier: 3, icon: "flame.fill", effect: (s) => { s.bladeOrbitBurnDamage = (s.bladeOrbitBurnDamage || 0) + 8; s.bladeOrbitBurnDuration = (s.bladeOrbitBurnDuration || 0) + 1.0; } },
      { name: "火环", description: "飞刀轨道留下火焰痕迹，灼烧经过的敌人", tier: 3, icon: "flame.fill", effect: (s) => { s.bladeOrbitFireTrail = true; } },
      { name: "熔岩飞刃", description: "飞刀伤害 +40%，命中留下熔岩地面", tier: 4, icon: "flame.fill", effect: (s) => { s.bladeOrbitDamage *= 1.40; s.bladeOrbitLavaPool = true; } },
      { name: "凤凰之翼", description: "飞刀旋转产生火焰翅膀，伤害 +60%", tier: 5, icon: "flame.fill", effect: (s) => { s.bladeOrbitDamage *= 1.60; s.bladeOrbitPhoenixWings = true; } },
      { name: "业火飞刃", description: "飞刀燃烧无法被扑灭，伤害随时间增加", tier: 5, icon: "flame.fill", effect: (s) => { s.bladeOrbitEternalFlame = true; s.bladeOrbitBurnDamage = (s.bladeOrbitBurnDamage || 0) + 12; } },

      { name: "涂毒术", description: "飞刀命中 15% 中毒 2秒", tier: 1, icon: "leaf.fill", effect: (s) => { s.bladeOrbitPoisonChance = Math.min(1, (s.bladeOrbitPoisonChance || 0) + 0.15); s.bladeOrbitPoisonDuration = Math.max(s.bladeOrbitPoisonDuration || 0, 2.0); s.bladeOrbitPoisonDamage = Math.max(s.bladeOrbitPoisonDamage || 0, 2); } },
      { name: "剧毒飞刃", description: "飞刀中毒几率 +25%，毒伤 +4", tier: 2, icon: "leaf.fill", effect: (s) => { s.bladeOrbitPoisonChance = Math.min(1, (s.bladeOrbitPoisonChance || 0) + 0.25); s.bladeOrbitPoisonDamage = (s.bladeOrbitPoisonDamage || 0) + 4; } },
      { name: "瘟疫之刃", description: "飞刀必定中毒，中毒蔓延到附近敌人", tier: 4, icon: "leaf.fill", effect: (s) => { s.bladeOrbitPoisonChance = 1.0; s.bladeOrbitPoisonSpread = true; } },
      { name: "毒雾弥漫", description: "飞刀轨道散发毒雾，持续伤害周围敌人", tier: 3, icon: "leaf.fill", effect: (s) => { s.bladeOrbitPoisonAura = true; } },
      { name: "致命毒素", description: "中毒的敌人受到所有伤害 +30%", tier: 3, icon: "leaf.fill", effect: (s) => { s.bladeOrbitPoisonWeaken = 0.30; } },
      { name: "腐蚀之刃", description: "中毒伤害 +10，持续时间 +2秒", tier: 3, icon: "leaf.fill", effect: (s) => { s.bladeOrbitPoisonDamage = (s.bladeOrbitPoisonDamage || 0) + 10; s.bladeOrbitPoisonDuration = (s.bladeOrbitPoisonDuration || 0) + 2.0; } },
      { name: "神经毒素", description: "中毒的敌人移动速度 -50%", tier: 4, icon: "leaf.fill", effect: (s) => { s.bladeOrbitPoisonSlow = 0.50; } },
      { name: "致死毒刃", description: "中毒层数达到5时直接杀死非Boss敌人", tier: 5, icon: "leaf.fill", effect: (s) => { s.bladeOrbitPoisonInstakill = true; s.bladeOrbitPoisonInstakillStacks = 5; } },

      { name: "雷刃", description: "飞刀命中 15% 释放闪电，伤害 +20%", tier: 1, icon: "bolt.fill", effect: (s) => { s.bladeOrbitShockChance = (s.bladeOrbitShockChance || 0) + 0.15; s.bladeOrbitDamage *= 1.20; } },
      { name: "电弧飞刀", description: "飞刀命中弹射闪电到附近1个敌人", tier: 2, icon: "bolt.fill", effect: (s) => { s.bladeOrbitChainCount = (s.bladeOrbitChainCount || 0) + 1; } },
      { name: "连锁闪电刃", description: "飞刀闪电弹射 +2 个目标", tier: 3, icon: "bolt.fill", effect: (s) => { s.bladeOrbitChainCount = (s.bladeOrbitChainCount || 0) + 2; } },
      { name: "雷暴飞刀", description: "飞刀命中 30% 眩晕敌人 0.5秒", tier: 2, icon: "bolt.fill", effect: (s) => { s.bladeOrbitStunChance = Math.min(1, (s.bladeOrbitStunChance || 0) + 0.30); s.bladeOrbitStunDuration = Math.max(s.bladeOrbitStunDuration || 0, 0.5); } },
      { name: "麻痹飞刃", description: "飞刀眩晕几率 +20%，眩晕时间 +0.3秒", tier: 3, icon: "bolt.fill", effect: (s) => { s.bladeOrbitStunChance = Math.min(1, (s.bladeOrbitStunChance || 0) + 0.20); s.bladeOrbitStunDuration = (s.bladeOrbitStunDuration || 0) + 0.3; } },
      { name: "雷霆万钧", description: "飞刀必定触发闪电，弹射 5 个目标", tier: 5, icon: "bolt.fill", effect: (s) => { s.bladeOrbitShockChance = 1.0; s.bladeOrbitChainCount = Math.max(s.bladeOrbitChainCount || 0, 5); } },
      { name: "磁暴飞刃", description: "飞刀产生磁场吸引附近敌人", tier: 3, icon: "bolt.fill", effect: (s) => { s.bladeOrbitMagneticPull = true; s.bladeOrbitMagneticRange = 80; } },
      { name: "雷神之怒", description: "每击杀一个敌人释放一道雷电", tier: 4, icon: "bolt.fill", effect: (s) => { s.bladeOrbitKillLightning = true; } },

      { name: "嗜血之刃", description: "飞刀命中 10% 吸血（伤害的 10%）", tier: 2, icon: "drop.fill", effect: (s) => { s.bladeOrbitLifestealChance = Math.min(1, (s.bladeOrbitLifestealChance || 0) + 0.10); s.bladeOrbitLifestealPercent = Math.max(s.bladeOrbitLifestealPercent || 0, 0.10); } },
      { name: "血刃强化", description: "飞刀吸血几率 +15%，吸血比例 +10%", tier: 3, icon: "drop.fill", effect: (s) => { s.bladeOrbitLifestealChance = Math.min(1, (s.bladeOrbitLifestealChance || 0) + 0.15); s.bladeOrbitLifestealPercent = (s.bladeOrbitLifestealPercent || 0) + 0.10; } },
      { name: "血族飞刃", description: "飞刀必定吸血（伤害的 30%）", tier: 5, icon: "drop.fill", effect: (s) => { s.bladeOrbitLifestealChance = 1.0; s.bladeOrbitLifestealPercent = Math.max(s.bladeOrbitLifestealPercent || 0, 0.30); } },
      { name: "生命飞刀", description: "每把飞刀每秒回复 0.5 生命", tier: 2, icon: "heart.fill", effect: (s) => { s.bladeOrbitRegenPerBlade = (s.bladeOrbitRegenPerBlade || 0) + 0.5; } },
      { name: "回春之刃", description: "每把飞刀每秒回复 1 生命", tier: 3, icon: "heart.fill", effect: (s) => { s.bladeOrbitRegenPerBlade = (s.bladeOrbitRegenPerBlade || 0) + 1.0; } },
      { name: "生命虹吸", description: "飞刀吸血比例 +15%", tier: 3, icon: "drop.fill", effect: (s) => { s.bladeOrbitLifestealPercent = (s.bladeOrbitLifestealPercent || 0) + 0.15; } },
      { name: "血祭飞刃", description: "消耗 5% 当前生命，飞刀伤害 +100%", tier: 4, icon: "drop.fill", effect: (s) => { s.bladeOrbitBloodSacrifice = true; s.bladeOrbitDamage *= 2.0; } },
      { name: "不死之刃", description: "飞刀吸血量超出上限时转化为临时护盾", tier: 5, icon: "heart.fill", effect: (s) => { s.bladeOrbitOverhealShield = true; } },

      { name: "精准飞刀", description: "飞刀暴击率 +10%", tier: 1, icon: "scope", effect: (s) => { s.bladeOrbitCritChance = (s.bladeOrbitCritChance || 0) + 0.10; } },
      { name: "致命飞刃", description: "飞刀暴击率 +15%，暴击伤害 +30%", tier: 2, icon: "scope", effect: (s) => { s.bladeOrbitCritChance = (s.bladeOrbitCritChance || 0) + 0.15; s.bladeOrbitCritDamage = (s.bladeOrbitCritDamage || 1.5) + 0.30; } },
      { name: "要害打击", description: "飞刀暴击伤害 +80%", tier: 3, icon: "scope", effect: (s) => { s.bladeOrbitCritDamage = (s.bladeOrbitCritDamage || 1.5) + 0.80; } },
      { name: "百步穿杨", description: "飞刀暴击率 +25%，暴击伤害 +50%", tier: 4, icon: "scope", effect: (s) => { s.bladeOrbitCritChance = (s.bladeOrbitCritChance || 0) + 0.25; s.bladeOrbitCritDamage = (s.bladeOrbitCritDamage || 1.5) + 0.50; } },
      { name: "必杀飞刀", description: "飞刀暴击率 +50%，暴击伤害 ×2", tier: 5, icon: "scope", effect: (s) => { s.bladeOrbitCritChance = (s.bladeOrbitCritChance || 0) + 0.50; s.bladeOrbitCritDamage = (s.bladeOrbitCritDamage || 1.5) * 2; } },
      { name: "穿刺飞刃", description: "飞刀穿透1个额外敌人", tier: 2, icon: "fan.fill", effect: (s) => { s.bladeOrbitPierce = (s.bladeOrbitPierce || 0) + 1; } },
      { name: "贯穿飞刀", description: "飞刀穿透3个额外敌人", tier: 3, icon: "fan.fill", effect: (s) => { s.bladeOrbitPierce = (s.bladeOrbitPierce || 0) + 3; } },
      { name: "无尽穿透", description: "飞刀穿透无限敌人", tier: 5, icon: "fan.fill", effect: (s) => { s.bladeOrbitPierce = 9999; } },
      { name: "弹射飞刀", description: "飞刀命中后弹射到附近 1 个敌人", tier: 2, icon: "arrow.triangle.branch", effect: (s) => { s.bladeOrbitBounce = (s.bladeOrbitBounce || 0) + 1; } },
      { name: "多重弹射", description: "飞刀弹射 +2 个目标", tier: 3, icon: "arrow.triangle.branch", effect: (s) => { s.bladeOrbitBounce = (s.bladeOrbitBounce || 0) + 2; } },

      { name: "追踪飞刃", description: "飞刀自动追踪最近的敌人", tier: 3, icon: "location.fill", effect: (s) => { s.bladeOrbitHoming = true; s.bladeOrbitHomingRange = 120; } },
      { name: "制导飞刀", description: "飞刀追踪范围 +60，追踪更加精准", tier: 4, icon: "location.fill", effect: (s) => { s.bladeOrbitHoming = true; s.bladeOrbitHomingRange = (s.bladeOrbitHomingRange || 120) + 60; s.bladeOrbitHomingAccuracy = (s.bladeOrbitHomingAccuracy || 0.5) + 0.3; } },
      { name: "刀刃反射", description: "飞刀反弹敌人子弹", tier: 3, icon: "arrow.uturn.left", effect: (s) => { s.bladeOrbitReflect = true; } },
      { name: "全方位防御", description: "飞刀反弹几率 100%，反弹伤害 +100%", tier: 5, icon: "arrow.uturn.left", effect: (s) => { s.bladeOrbitReflect = true; s.bladeOrbitReflectDamage = (s.bladeOrbitReflectDamage || 1) * 2; } },
      { name: "爆裂飞刃", description: "飞刀命中产生小范围爆炸", tier: 3, icon: "burst.fill", effect: (s) => { s.bladeOrbitExplosion = true; s.bladeOrbitExplosionRadius = 30; } },
      { name: "核爆飞刀", description: "飞刀爆炸范围 +40，伤害 +50%", tier: 4, icon: "burst.fill", effect: (s) => { s.bladeOrbitExplosion = true; s.bladeOrbitExplosionRadius = (s.bladeOrbitExplosionRadius || 30) + 40; s.bladeOrbitDamage *= 1.50; } },
      { name: "分裂飞刀", description: "飞刀命中后分裂成 2 把小飞刀", tier: 3, icon: "arrow.branch", effect: (s) => { s.bladeOrbitSplit = (s.bladeOrbitSplit || 0) + 2; } },
      { name: "连锁分裂", description: "分裂的飞刀也可以分裂", tier: 5, icon: "arrow.branch", effect: (s) => { s.bladeOrbitSplitChain = true; s.bladeOrbitSplit = Math.max(s.bladeOrbitSplit || 0, 2); } },
      { name: "回旋飞刀", description: "飞刀飞出后返回，造成两次伤害", tier: 2, icon: "arrow.uturn.backward", effect: (s) => { s.bladeOrbitBoomerang = true; } },
      { name: "影刃", description: "每把飞刀生成一把幻影飞刀（50%伤害）", tier: 4, icon: "moon.fill", effect: (s) => { s.bladeOrbitShadowBlade = true; s.bladeOrbitShadowDamageMult = 0.50; } },
      { name: "共振飞刃", description: "飞刀之间产生能量链，伤害链上的敌人", tier: 4, icon: "waveform", effect: (s) => { s.bladeOrbitResonance = true; } },
      { name: "时停飞刀", description: "飞刀暴击时冻结时间 0.3秒", tier: 5, icon: "clock.fill", effect: (s) => { s.bladeOrbitTimeStop = true; s.bladeOrbitTimeStopDuration = 0.3; } },

      { name: "刀盾", description: "飞刀提供 5% 伤害减免（每把）", tier: 2, icon: "shield.fill", effect: (s) => { s.bladeOrbitDamageReduction = (s.bladeOrbitDamageReduction || 0) + 0.05; } },
      { name: "铁壁刀阵", description: "飞刀提供 10% 伤害减免（每把）", tier: 3, icon: "shield.fill", effect: (s) => { s.bladeOrbitDamageReduction = (s.bladeOrbitDamageReduction || 0) + 0.10; } },
      { name: "刀阵漩涡", description: "飞刀高速旋转形成漩涡，持续吸引半径内敌人靠近", tier: 4, icon: "tornado", effect: (s) => { s.bladeOrbitVortex = true; s.bladeOrbitVortexRange = 120; s.bladeOrbitVortexStrength = 60; } },
      { name: "反击飞刃", description: "受到伤害时所有飞刀伤害 +20%（持续3秒）", tier: 2, icon: "shield.fill", effect: (s) => { s.bladeOrbitCounterAttack = true; s.bladeOrbitCounterBonus = 0.20; } },
      { name: "荆棘飞刀", description: "敌人被飞刀命中后，攻击该敌人回复1生命", tier: 3, icon: "leaf.fill", effect: (s) => { s.bladeOrbitThornHeal = true; } },
      { name: "绝对防御", description: "飞刀数量>10时，免疫所有控制效果", tier: 5, icon: "shield.fill", effect: (s) => { s.bladeOrbitCCImmune = true; s.bladeOrbitCCImmuneThreshold = 10; } },

      { name: "刀神降临", description: "飞刀数量 +5，伤害 +50%，旋转速度 +50%", tier: 5, icon: "sparkles", effect: (s) => { s.bladeOrbitCount += 5; s.bladeOrbitDamage *= 1.50; s.bladeOrbitSpeed *= 1.50; } },
      { name: "无限刀阵", description: "飞刀数量翻倍", tier: 5, icon: "infinity", effect: (s) => { s.bladeOrbitCount *= 2; } },
      { name: "万象归一", description: "飞刀获得 冰冻10%+点燃10%+中毒10%+眩晕10%", tier: 4, icon: "sparkles", effect: (s) => { s.bladeOrbitFreezeChance = Math.min(1, (s.bladeOrbitFreezeChance || 0) + 0.10); s.bladeOrbitFreezeDuration = Math.max(s.bladeOrbitFreezeDuration || 0, 0.5); s.bladeOrbitBurnChance = Math.min(1, (s.bladeOrbitBurnChance || 0) + 0.10); s.bladeOrbitBurnDuration = Math.max(s.bladeOrbitBurnDuration || 0, 1.0); s.bladeOrbitBurnDamage = Math.max(s.bladeOrbitBurnDamage || 0, 2); s.bladeOrbitPoisonChance = Math.min(1, (s.bladeOrbitPoisonChance || 0) + 0.10); s.bladeOrbitPoisonDuration = Math.max(s.bladeOrbitPoisonDuration || 0, 1.5); s.bladeOrbitPoisonDamage = Math.max(s.bladeOrbitPoisonDamage || 0, 2); s.bladeOrbitStunChance = Math.min(1, (s.bladeOrbitStunChance || 0) + 0.10); s.bladeOrbitStunDuration = Math.max(s.bladeOrbitStunDuration || 0, 0.3); } },
      { name: "飞刀大师", description: "所有飞刀效果提升 50%", tier: 5, icon: "crown.fill", effect: (s) => { s.bladeOrbitDamage *= 1.50; s.bladeOrbitScale *= 1.20; s.bladeOrbitSpeed *= 1.20; s.bladeOrbitRadius += 20; } },
      { name: "天降飞刀", description: "每 3 秒从天空降下飞刀攻击随机敌人", tier: 3, icon: "arrow.down", effect: (s) => { s.bladeOrbitSkyfall = true; s.bladeOrbitSkyfallInterval = 3.0; } },
      { name: "刀阵自爆", description: "按住技能键飞刀全部射出造成巨额伤害，之后重新生成", tier: 4, icon: "burst.fill", effect: (s) => { s.bladeOrbitBurst = true; } },
      { name: "轮回飞刃", description: "飞刀击杀敌人时有 20% 几率额外获得经验", tier: 2, icon: "arrow.clockwise", effect: (s) => { s.bladeOrbitExpBonus = 0.20; } },
      { name: "永恒刀阵", description: "飞刀数量 +10，伤害 +100%，半径 +50，全属性强化", tier: 5, icon: "crown.fill", effect: (s) => { s.bladeOrbitCount += 10; s.bladeOrbitDamage *= 2.0; s.bladeOrbitRadius += 50; s.bladeOrbitSpeed *= 1.30; s.bladeOrbitScale *= 1.30; } }
    ];
  }

  Skills.buildExtraBladeSkills = buildExtraBladeSkills;
})();
